blueprint:
  domain: automation
  name: Music Assistant - Local LLM Enhanced Voice Support Blueprint
  source_url: https://github.com/music-assistant/voice-support/blob/main/local-assist-blueprint/mass_llm_enhanced_assist_blueprint_en.yaml
  description: '
    ![Image](https://github.com/music-assistant/voice-support/blob/main/assets/music-assistant.png?raw=true)

    # Play media using voice commands with LLM assistance

    ### Usage

    All sentences must:

    * start with the words `Play` or `Listen to` followed by a query about what you want to play

    * then be optionally followed by an area name or device name to play the music on


    #### Acceptable variations

    There are acceptable variations to some words and inclusion of the word `the` is optional.

    #### Examples

    ```

    Play the artist Pink Floyd in the kitchen

    Listen to album Jagged Little Pill in the study

    Listen to the album Greatest Hits by the artist James Taylor in the kitchen

    Play track New Years Day in the bedroom

    Play track New Years Day in the bedroom using radio mode

    Play the song A Hard Days Night by Billy Joel in the bedroom

    Listen to the playlist Classic Rock in the study

    Listen to the radio station BBC Radio 1 in the bedroom

    Play the album Classical Nights on the Bedroom Sonos Speaker

    Listen to the record Classical Nights on the Bedroom Sonos Speaker

    Play the band U2

    Play music by the composer from oppenheimer

    Play the album that has the nude baby swimming in the water on the cover

    ```
  '
  input:
    default_player_entity_id_input:
      name: Default Media Player
      selector:
        entity:
          filter:
            integration: music_assistant
            domain: media_player
    mass_llm_id_input:
      name: Music Assistant LLM
      selector:
        entity:
          filter:
            domain: conversation
triggers:
  - trigger: conversation
    command:
      - "(play|listen to) {query}"
    id: llm
conditions: []
actions:
  - variables:
      default_player_entity_id: !input default_player_entity_id_input
      query: "{{ trigger.slots.query }}"
      assist_device_id: "{{ trigger.device_id }}"
      mass_llm: !input mass_llm_id_input
  - action: conversation.process
    data:
      text: "{{ query }}"
      agent_id: "{{ mass_llm }}"
    response_variable: result
  - action: music_assistant.play_media
    data:
      media_id: '{{ result.action_data.media_id }}'
      media_type: '{{ result.action_data.media_type }}'
      radio_mode: '{{ result.action_data.radio_mode }}'
      {%- if 'artist' in result.action_data %}
      artist: '{{ result.action_data.artist }}'
      {%- endif %}
      {%- if 'album' in result.action_data %}
      album: '{{ result.action_data.album }}'
      {%- endif %}
    target:
      {%- if 'entity_id' in result.target_data %}
      entity_id: '{{ result.target_data.entity_id }}'
      {%- endif %}
      {%- else %}
      area_id: '{{ result.target_data.area_id }}'
      {%- endif %}
  - set_conversation_response: >- 
      {{ result.action_data.media_id }} playing 
      {%- if 'entity_id' in result.target_data %}
      on {{ result.target_data.entity_id }}.
      {%- endif %}
      {%- else %}
      in the {{ result.target_data.area_id }}.
      {%- endif %}
mode: single
